# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Machine See, Machine Do
email: gregor.koe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    On this blog you can eventually find posts about topics in ML, as well as some about interesting gadgets (drones?). 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: GregorKoe
github_username:  GregorKoehler

# Build settings
markdown: kramdown
# other themes: https://gitlab.com/andrewbanchich/forty-jekyll-theme/blob/master/README.md
# http://www.rubydoc.info/gems/jekyll-theme-kagami/0.1.12
# https://github.com/aron-bordin/neo-hpstr-jekyll-theme/
# http://www.rubydoc.info/gems/cosy-jekyll-theme/1.1.1
# http://www.rubydoc.info/gems/jekyll-theme-heidi/3.0.2
# https://github.com/desiredpersona/minimal-jekyll-theme
# https://github.com/daattali/beautiful-jekyll/tree/gem#readme
# http://hyde.getpoole.com
# https://github.com/brettinternet/minimaless
# https://github.com/gadgetry-io/theme
    # Installation
    # Add this line to your Jekyll site's Gemfile:

    #gem "photoblog-theme"
    #And add this line to your Jekyll site's _config.yml:

    #theme: photoblog-theme
    #And then execute:

    #$ bundle
    #Or install it yourself as:

    #$ gem install photoblog-theme

theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
